[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rewind-timeline"
description = "Linux timeline collector and monitoring tool"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
    "psutil>=5.9.0",
    "watchdog>=4.0.0",
]
license = "MIT"
authors = [{ name = "DarkGlitch" }]

[project.urls]
Homepage = "https://github.com/LaVenganzaDelLadron/"
Repository = "https://github.com/LaVenganzaDelLadron/rewind.git"

[project.scripts]
rewind = "rewind:main"

[tool.setuptools]
py-modules = ["database", "rewind"]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.dynamic]
version = { attr = "utils.version.__version__" }
