[metadata]
name = rewind-timeline
version = 0.1.0
author = LaVenganzaDelLadron
author_email = darkglitch5417@gmail.com
desciption =The repo implements Rewind, a CLI tool that acts as a Linux “time machine” by collecting system events (package changes from pacman logs, service state changes from systemctl, performance threshold alerts via psutil, executed shell commands from /.bash_history, and filesystem create/modify/delete events via watchdog) and storing them in a local SQLite database (/.rewind.db). It then lets users view events for today/yesterday, search events by keyword, and display basic statistics about the recorded timeline.
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
url = https://github.com/LaVenganzaDelLadron/rewind.git
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8

entry_points =
    console_scripts =
        rewind = rewind:main
